/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CommunauteRouteImport } from './routes/communaute'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as RejoindreRouteImport } from './routes/rejoindre'
import { Route as TableauDeBordRouteImport } from './routes/tableau-de-bord'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunauteRoute = CommunauteRouteImport.update({
  id: '/communaute',
  path: '/communaute',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const RejoindreRoute = RejoindreRouteImport.update({
  id: '/rejoindre',
  path: '/rejoindre',
  getParentRoute: () => rootRouteImport,
} as any)
const TableauDeBordRoute = TableauDeBordRouteImport.update({
  id: '/tableau-de-bord',
  path: '/tableau-de-bord',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/communaute': typeof CommunauteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/rejoindre': typeof RejoindreRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/communaute': typeof CommunauteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/rejoindre': typeof RejoindreRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/communaute': typeof CommunauteRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/rejoindre': typeof RejoindreRoute
  '/tableau-de-bord': typeof TableauDeBordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/communaute'
    | '/confidentialite'
    | '/rejoindre'
    | '/tableau-de-bord'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/communaute'
    | '/confidentialite'
    | '/rejoindre'
    | '/tableau-de-bord'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/communaute'
    | '/confidentialite'
    | '/rejoindre'
    | '/tableau-de-bord'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CommunauteRoute: typeof CommunauteRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  RejoindreRoute: typeof RejoindreRoute
  TableauDeBordRoute: typeof TableauDeBordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communaute': {
      id: '/communaute'
      path: '/communaute'
      fullPath: '/communaute'
      preLoaderRoute: typeof CommunauteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejoindre': {
      id: '/rejoindre'
      path: '/rejoindre'
      fullPath: '/rejoindre'
      preLoaderRoute: typeof RejoindreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tableau-de-bord': {
      id: '/tableau-de-bord'
      path: '/tableau-de-bord'
      fullPath: '/tableau-de-bord'
      preLoaderRoute: typeof TableauDeBordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CommunauteRoute: CommunauteRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  RejoindreRoute: RejoindreRoute,
  TableauDeBordRoute: TableauDeBordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
